version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-portfolio"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1i63gutm8idiv"
s3_prefix = "sam-portfolio"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "DomainName=\"askininan.com\""
