AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  "askininan.com" Portfolio-Website backend IaC 

Resources:

# Lambda function 
  Counter:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Lambda/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        Counter:
          Type: Api
          Properties:
            Path: /get
            Method: get
      Environment:
        Variables: 
          databaseName : !Ref ResumeCounterTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ResumeCounterTable

# DynamoDB table for counter data
  ResumeCounterTable:
    Type: AWS::Serverless::SimpleTable
    
Outputs:
  CounterApi:
    Description: "API Gateway endpoint URL for Prod stage for Counter function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get"