name: Deploy AWS SAM Stack
#ref: https://aws.amazon.com/blogs/compute/using-github-actions-to-deploy-serverless-applications/

on:
  push:
    branches:
      - main

permissions:
      id-token: write
      contents: read

jobs:
  samBuildDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::526450518584:role/S3+CloudFormation_Access
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: eu-central-1
      

# Install env dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install boto3
          pip install moto[ec2,s3,all]
          pip install -r Lambda/requirements.txt
        

# sam build 
      - run: sam build --use-container -t template.yaml --debug
# sam deploy
      - run: sam deploy -t template.yaml --config-file samconfig.toml --debug --no-confirm-changeset --no-fail-on-empty-changeset