name: Deploy AWS SAM Stack
#ref: https://aws.amazon.com/blogs/compute/using-github-actions-to-deploy-serverless-applications/

on:
  push:
    branches:
      - main


jobs:
  samBuildDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ASKININAN_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ASKININAN_SECRET_ACCESS_KEY }}
          aws-region: eu-cental-1
      

# Install env dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install boto3
          pip install moto[ec2,s3,all]
          pip install -r Lambda/requirements.txt
        

# # Run Unit tests
#     - name: Unit test Lambda visitor counter funtion
#           run: python Lambda/UnitTest.py


# sam build 
      - run: sam build --use-container -t template.yaml --debug
# sam deploy
      - run: sam deploy -t template.yaml --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM